security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app:
            entity:
                class: App\Entity\User
                property: email

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_ENSEIGNANT: ROLE_USER
        ROLE_ETUDIANT: ROLE_USER
        ROLE_PARENT: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app
            stateless: false
            context: user_session

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/enseignant, roles: ROLE_ENSEIGNANT }
        - { path: ^/etudiant, roles: ROLE_ETUDIANT }
        - { path: ^/parent, roles: ROLE_PARENT }
        - { path: ^/reclamation/new, roles: PUBLIC_ACCESS }

